# Generated by Django 5.0.3 on 2024-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0015_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
